version: '3.8'
services: 
    web:
        build:
            context: ./shorturl
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:     
            - mongo
            
    mongo:
        container_name: mongo
        image: mongo
        volumes: 
          - ./data:/data/db
        ports: 
          - "27017:27017" 
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pass