apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"