apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: yasamanhbn/final_shorturl
        ports:
          - containerPort: 8080
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /app/config/config.json
            subPath: production-config.json
            name: config-map

        env:
          - name: CONFIG_MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
                
          - name: CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password

      volumes:
        - name: config-map
          configMap:
            name: shorturl-config


---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

